//Script generated by SceneScriptGenerator.cs

namespace StorkStudios.CoreNest
{
	public enum Scene
	{
		MainMenu = 0,
		LabirynthOne = 1,
		FNFOne = 2,
		VNOne = 3,
		VNTwo = 4,
		LabirynthTwo = 5,
		FNFTwo = 6,
	}
	
	public static class SceneExtensions
	{
		public static int GetBuildIndex(this Scene value)
		{
			return (int)value;
		}
	}
}
