//Script generated by SceneScriptGenerator.cs

namespace StorkStudios.CoreNest
{
	public enum Scene
	{
		LabirynthOne = 0,
		FNFOne = 1,
		VNOne = 2,
		VNTwo = 3,
	}
	
	public static class SceneExtensions
	{
		public static int GetBuildIndex(this Scene value)
		{
			return (int)value;
		}
	}
}
